#!/usr/bin/env bash
# Promote a ready roadmap item into the implementation behaviour-tree loop.
#
# This script does not build the feature. It creates a dedicated git worktree
# and writes a normalized docs/plans/*roadmap-*.md build plan there. The
# original implementation BT can then run inside that worktree with /next-action.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/roadmap/promote-ready-item-to-worktree.sh [--dry-run] <item-id>

Creates:
  .worktrees/roadmap-<id>-<slug>/
  branch auto/roadmap-<id>-<slug>
  docs/plans/YYYY-MM-DD-roadmap-<id>-<slug>.md inside the worktree

Then run the implementation loop from the printed worktree:
  cd .worktrees/roadmap-<id>-<slug>
  .claude/hooks/setup-next-action.sh
  /loop /next-action
EOF
}

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=1
  shift
fi

ITEM_ID="${1:-}"
if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" = "-h" ] || [ "$ITEM_ID" = "--help" ]; then
  usage
  exit 0
fi

case "$ITEM_ID" in
  ''|*[!0-9]*)
    echo "Item id must be an integer: $ITEM_ID" >&2
    exit 1
    ;;
esac

REPO="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
cd "$REPO"

ROADMAP_DIR="$REPO/docs/roadmap"
WORKTREE_ROOT="$REPO/.worktrees"

frontmatter_value() {
  local file="$1"
  local key="$2"
  local fallback="${3:-}"

  if [ ! -f "$file" ]; then
    printf '%s\n' "$fallback"
    return
  fi

  local value
  value="$(awk -v key="$key" '
    NR == 1 && $0 == "---" { in_fm = 1; next }
    in_fm && $0 == "---" { exit }
    in_fm && index($0, key ":") == 1 {
      sub("^[^:]+:[[:space:]]*", "")
      print
      exit
    }
  ' "$file")"

  if [ -n "$value" ]; then
    printf '%s\n' "$value" | sed 's/^"//; s/"$//'
  else
    printf '%s\n' "$fallback"
  fi
}

feature_dir_for_id() {
  local id="$1"
  local readme
  while IFS= read -r readme; do
    if [ "$(frontmatter_value "$readme" "id" "")" = "$id" ]; then
      dirname "$readme"
      return 0
    fi
  done < <(find "$ROADMAP_DIR" -mindepth 2 -maxdepth 2 -name README.md -type f | sort)
  return 1
}

FEATURE_DIR="$(feature_dir_for_id "$ITEM_ID" || true)"
if [ -z "$FEATURE_DIR" ]; then
  echo "No roadmap item found with id $ITEM_ID" >&2
  exit 1
fi

SLUG="$(basename "$FEATURE_DIR")"
TITLE="$(frontmatter_value "$FEATURE_DIR/README.md" "title" "$SLUG")"
STAGE="$(frontmatter_value "$FEATURE_DIR/README.md" "stage" "unknown")"

for required in "implementation-handoff.md" "spec.md" "plan.md"; do
  if [ ! -s "$FEATURE_DIR/$required" ]; then
    echo "Roadmap item $ITEM_ID ($TITLE) is not ready: missing $FEATURE_DIR/$required" >&2
    exit 1
  fi
done

if [ "$STAGE" != "ready-for-build-queue" ]; then
  echo "Roadmap item $ITEM_ID ($TITLE) has stage '$STAGE', expected 'ready-for-build-queue'." >&2
  echo "Refusing to promote until the PM selector has marked it ready." >&2
  exit 1
fi

BRANCH="auto/roadmap-${ITEM_ID}-${SLUG}"
WORKTREE="$WORKTREE_ROOT/roadmap-${ITEM_ID}-${SLUG}"
PLAN_FILE="docs/plans/$(date -u +"%Y-%m-%d")-roadmap-${ITEM_ID}-${SLUG}.md"

if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
  echo "Branch already exists: $BRANCH" >&2
  exit 1
fi

if [ -e "$WORKTREE" ]; then
  echo "Worktree path already exists: $WORKTREE" >&2
  exit 1
fi

TASKS=()
while IFS= read -r task; do
  [ -n "$task" ] && TASKS+=("$task")
done < <(awk '
  function flush_phase() {
    if (phase != "" && phase_has_child == 0) {
      print phase
    }
  }
  /^### / {
    flush_phase()
    phase = substr($0, 5)
    phase_has_child = 0
    next
  }
  /^#### / {
    phase_has_child = 1
    print substr($0, 6)
    next
  }
  END {
    flush_phase()
  }
' "$FEATURE_DIR/plan.md")

if [ "${#TASKS[@]}" -eq 0 ]; then
  echo "Could not extract build tasks from $FEATURE_DIR/plan.md" >&2
  exit 1
fi

echo "Roadmap item: $ITEM_ID $TITLE"
echo "Source:       docs/roadmap/$SLUG/"
echo "Worktree:    $WORKTREE"
echo "Branch:      $BRANCH"
echo "Build plan:  $PLAN_FILE"
echo "Tasks:       ${#TASKS[@]}"

if [ "$DRY_RUN" -eq 1 ]; then
  echo
  echo "Dry run only. No worktree or files created."
  exit 0
fi

mkdir -p "$WORKTREE_ROOT"
git worktree add -b "$BRANCH" "$WORKTREE" HEAD

mkdir -p "$WORKTREE/docs/plans"
{
  echo "# Roadmap Build Plan: $TITLE"
  echo
  echo "**Status:** Active."
  echo "**Roadmap item:** $ITEM_ID"
  echo "**Roadmap source:** \`docs/roadmap/$SLUG/\`"
  echo
  echo "This plan was generated by \`scripts/roadmap/promote-ready-item-to-worktree.sh\`."
  echo "Run it only inside the dedicated worktree for \`$BRANCH\`."
  echo
  echo "## Architecture"
  echo
  echo "Use \`docs/roadmap/$SLUG/implementation-handoff.md\` as the authoritative entry point."
  echo "Follow the guardrails in \`docs/roadmap/$SLUG/architecture.md\` and the accepted decisions in \`docs/roadmap/$SLUG/architecture-review.md\`."
  echo "Do not re-litigate PM decisions in implementation; if a task exposes a missing product decision, write a note to \`.claude/state/inbox/\` and stop."
  echo
  echo "## Environment"
  echo
  echo "Build in this worktree on branch \`$BRANCH\`."
  echo "Use the normal implementation behaviour tree: \`.claude/hooks/setup-next-action.sh\` then \`/next-action\` or \`/loop /next-action\`."
  echo "Keep implementation slices narrow. Each task below maps back to a section in \`docs/roadmap/$SLUG/plan.md\`."
  echo

  task_number=1
  for task in "${TASKS[@]}"; do
    echo "## Task $task_number: $task"
    echo
    echo "- [ ] Execute the \`$task\` section from \`docs/roadmap/$SLUG/plan.md\`, using \`docs/roadmap/$SLUG/implementation-handoff.md\` for acceptance criteria, non-goals, source locations, gates, and test expectations."
    echo
    task_number=$((task_number + 1))
  done
} > "$WORKTREE/$PLAN_FILE"

git -C "$WORKTREE" add "$PLAN_FILE"
git -C "$WORKTREE" commit -m "plan(roadmap): promote item $ITEM_ID $SLUG"

git -C "$WORKTREE" status --short
"$WORKTREE/.claude/hooks/setup-next-action.sh" >/dev/null

echo
echo "Promoted roadmap item $ITEM_ID to implementation worktree."
echo "Next:"
echo "  cd $WORKTREE"
echo "  cat .claude/state/next-action.md"
echo "  /loop /next-action"
